version: '3'
services:
  node:
    image: node:22.4.0
    ports:
      - "43035:3000"
    volumes:
      - .:/usr/src
    working_dir: /usr/src
    command: sh -c "if [ ! -e node_modules ]; then npm install; fi && node index.js"
    restart: unless-stopped
