global:
  scrape_interval: 500ms
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - PROMETHUS_SERVER:9090

  - job_name: webtiles-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - webtiles-exporter:9100
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*?)\..+'
        target_label: 'instance'
        replacement: '$1'
